services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .env
    volumes:
      - "./:/app/backend"
    ports:
      - 81:8080
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: ticketing-backend

  dbui:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@example.com
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword
    depends_on:
      - db